services:
  mysql:
    image: mysql:latest
    container_name: mysql_restore
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

